version: '3.9'
services:
  performance:
    container_name: performance-evaluation
    image: sembravaqualcuno/performance-evaluation
    env_file:
      - performance.env
    networks:
      - DataProxy-network
      
networks:
  DataProxy-network:
    external: true
      
