{
 "title": "Device 1",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sensor-data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.device_id == \"1\" and\r\n    r._field == \"temp\"\r\n  )"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sensor-data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.device_id == \"1\" and\r\n    r._field == \"hum\"\r\n  )"
    }
   ]
  },
  {
   "title": "Gas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sensor-data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.device_id == \"1\" and\r\n    r._field == \"gas\"\r\n  )"
    }
   ]
  },
  {
   "title": "AQI",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"sensor-data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.device_id == \"1\" and\r\n    r._field == \"AQI\"\r\n  )"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"sensor-data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.device_id == \"1\" and\r\n    r._field == \"RSSI\"\r\n  )"
    }
   ]
  }
 ]
}